In [38]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler


departure_time stops   arrival_time     class  duration  days_left  \
0             Evening  zero          Night   Economy      2.17          1   
1       Early_Morning  zero        Morning   Economy      2.33          1   
2       Early_Morning  zero  Early_Morning   Economy      2.17          1   
3             Morning  zero      Afternoon   Economy      2.25          1   
4             Morning  zero        Morning   Economy      2.33          1   
...               ...   ...            ...       ...       ...        ...   
270133  Early_Morning   one          Night  Business     17.25         49   
270134        Morning   one        Evening  Business     10.08         49   
270135      Afternoon   one          Night  Business     10.42         49   
270136  Early_Morning   one        Evening  Business     10.00         49   
270137        Morning   one        Evening  Business     10.08         49   

        price  
0        5953  
1        5953  
2        5956  
3        5955  
4        5955  
...       ...  
270133  68739  
270134  69265  
270135  77105  
270136  81585  
270137  81585  

[270138 rows x 7 columns]

In [39]:
df = pd.read_csv("Flight_Price_Dataset_Q2.csv")
df

departure_time  stops  arrival_time  class  duration  days_left  price
0                    3      0             4      1      2.17          1   5953
1                    0      0             1      1      2.33          1   5953
2                    0      0             0      1      2.17          1   5956
3                    1      0             2      1      2.25          1   5955
4                    1      0             1      1      2.33          1   5955
...                ...    ...           ...    ...       ...        ...    ...
270133               0      1             4      5     17.25         49  68739
270134               1      1             3      5     10.08         49  69265
270135               2      1             4      5     10.42         49  77105
270136               0      1             3      5     10.00         49  81585
270137               1      1             3      5     10.08         49  81585

[270138 rows x 7 columns]

In [43]:
df["stops"] = df["stops"].map({"zero": 0, "one": 1, "two_or_more": 2})

df['arrival_time'] = df['arrival_time'].map({'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2,
                                             'Evening': 3, 'Night': 4, 'Late_Night': 5})

df['departure_time'] = df['departure_time'].map({'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2,
                                                 'Evening': 3, 'Night': 4, 'Late_Night': 5})

df['class'] = df['class'].map({'Economy': 1, 'Business': 5})
df

departure_time  stops  arrival_time  class  duration  days_left  b
0                    3      0             4      1      2.17          1  1
1                    0      0             1      1      2.33          1  1
2                    0      0             0      1      2.17          1  1
3                    1      0             2      1      2.25          1  1
4                    1      0             1      1      2.33          1  1
...                ...    ...           ...    ...       ...        ... ..
270133               0      1             4      5     17.25         49  1
270134               1      1             3      5     10.08         49  1
270135               2      1             4      5     10.42         49  1
270136               0      1             3      5     10.00         49  1
270137               1      1             3      5     10.08         49  1

[270138 rows x 7 columns]

In [163]:
x = df.iloc[0:, 0:6]
# x = np.array(x)
# # x = (x - x.mean()) / x.std()
# x = pd.DataFrame(x)
x['b'] = 1
x

array([[0.        , 0.        , 1.        , ..., 0.02734694, 0.        ,
        0.03974878],
       [0.        , 0.        , 1.        , ..., 0.03061224, 0.        ,
        0.03974878],
       [0.        , 0.        , 1.        , ..., 0.02734694, 0.        ,
        0.03977338],
       ...,
       [1.        , 0.        , 0.        , ..., 0.19571429, 1.        ,
        0.62312448],
       [1.        , 0.        , 0.        , ..., 0.18714286, 1.        ,
        0.65985603],
       [1.        , 0.        , 0.        , ..., 0.18877551, 1.        ,
        0.65985603]])

In [ ]:
# x = np.array(x)
# # x = (x - x.mean()) / x.std()
# x = pd.DataFrame(x)
x['b'] = 1
x

In [14]:
y = df["price"].values

x = df.iloc[0:, 0:6]
x = np.array(x)
x = (x - x.mean()) / x.std()
x = pd.DataFrame(x)
x['b'] = 1
x = np.array(x)
x

array([[-0.42160947, -0.69302263, -0.33113842, ..., -0.49670045,
        -0.60255158,  1.        ],
       [-0.69302263, -0.69302263, -0.60255158, ..., -0.48222508,
        -0.60255158,  1.        ],
       [-0.69302263, -0.69302263, -0.69302263, ..., -0.49670045,
        -0.60255158,  1.        ],
       ...,
       [-0.51208052, -0.60255158, -0.33113842, ...,  0.24968573,
         3.74005889,  1.        ],
       [-0.69302263, -0.60255158, -0.42160947, ...,  0.21168789,
         3.74005889,  1.        ],
       [-0.60255158, -0.60255158, -0.42160947, ...,  0.21892557,
         3.74005889,  1.        ]])

In [8]:
y = (y - y.mean()) / y.std()
y

array([-0.65820293, -0.65820293, -0.65807075, ...,  2.47665663,
        2.67403929,  2.67403929])

In [29]:
coef = np.zeros(7)
d = x.dot(coef)
d

array([0., 0., 0., ..., 0., 0., 0.])

In [18]:
y = df["price"].values
d - y

array([ -5953.,  -5953.,  -5956., ..., -77105., -81585., -81585.])

In [28]:
t = np.dot(np.transpose(np.dot(x, coef) - y), x) * 2/len(x)
t

array([ 21780.46082859,  25268.30733125,  18756.77833428,  13332.33688036,
       -23286.2590386 , -64255.41648656, -41784.5024543 ])

In [138]:
x = df.drop("price", axis=1).values
y = df["price"].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.6, shuffle=False)
x_train

array([[ 1.  ,  2.17,  1.  ],
       [ 1.  ,  2.33,  1.  ],
       [ 1.  ,  2.17,  1.  ],
       ...,
       [ 1.  , 10.75,  4.  ],
       [ 1.  , 11.58,  4.  ],
       [ 1.  , 14.08,  4.  ]])

In [113]:

df["stops"] = df["stops"].map({"zero": 0, "one": 1, "two_or_more": 2})

df['arrival_time'] = df['arrival_time'].map({'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2,
                                             'Evening': 3, 'Night': 4, 'Late_Night': 5})

df['departure_time'] = df['departure_time'].map({'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2,
                                                 'Evening': 3, 'Night': 4, 'Late_Night': 5})

df['class'] = df['class'].map({'Economy': 0, 'Business': 1})
df

departure_time  stops   arrival_time  class  duration  days_left  \
0                  NaN    NaN          Night    NaN      2.17          1   
1                  NaN    NaN        Morning    NaN      2.33          1   
2                  NaN    NaN  Early_Morning    NaN      2.17          1   
3                  NaN    NaN      Afternoon    NaN      2.25          1   
4                  NaN    NaN        Morning    NaN      2.33          1   
...                ...    ...            ...    ...       ...        ...   
270133             NaN    NaN          Night    NaN     17.25         49   
270134             NaN    NaN        Evening    NaN     10.08         49   
270135             NaN    NaN          Night    NaN     10.42         49   
270136             NaN    NaN        Evening    NaN     10.00         49   
270137             NaN    NaN        Evening    NaN     10.08         49   

        price  Afternoon  Early_Morning  Evening  ...  Evening  Late_Night  \
0        5953      False          False    False  ...    False       False   
1        5953      False          False    False  ...    False       False   
2        5956      False           True    False  ...    False       False   
3        5955       True          False    False  ...    False       False   
4        5955      False          False    False  ...    False       False   
...       ...        ...            ...      ...  ...      ...         ...   
270133  68739      False          False    False  ...    False       False   
270134  69265      False          False     True  ...     True       False   
270135  77105      False          False    False  ...    False       False   
270136  81585      False          False     True  ...     True       False   
270137  81585      False          False     True  ...     True       False   

        Morning  Night  Afternoon  Early_Morning  Evening  Late_Night  \
0         False   True      False          False    False       False   
1          True  False      False          False    False       False   
2         False  False      False           True    False       False   
3         False  False       True          False    False       False   
4          True  False      False          False    False       False   
...         ...    ...        ...            ...      ...         ...   
270133    False   True      False          False    False       False   
270134    False  False      False          False     True       False   
270135    False   True      False          False    False       False   
270136    False  False      False          False     True       False   
270137    False  False      False          False     True       False   

        Morning  Night  
0         False   True  
1          True  False  
2         False  False  
3         False  False  
4          True  False  
...         ...    ...  
270133    False   True  
270134    False  False  
270135    False   True  
270136    False  False  
270137    False  False  

[270138 rows x 25 columns]

In [98]:
x = df.drop("price", axis=1).values
print(x)

[[ 3.    0.    4.    0.    2.17  1.  ]
 [ 0.    0.    1.    0.    2.33  1.  ]
 [ 0.    0.    0.    0.    2.17  1.  ]
 ...
 [ 2.    1.    4.    1.   10.42 49.  ]
 [ 0.    1.    3.    1.   10.   49.  ]
 [ 1.    1.    3.    1.   10.08 49.  ]]


In [107]:
scaler = MaxAbsScaler
data = np.array(df)
x_normalized = scaler.
x_normalized

TypeError: TransformerMixin.fit_transform() missing 1 required positional argument: 'X'

In [67]:
y = df["price"].values
print(y)

[ 5953  5953  5956 ... 77105 81585 81585]


In [70]:
df.corr()

departure_time     stops  arrival_time     class  duration  \
departure_time        1.000000 -0.070057     -0.079846  0.029657  0.131420   
stops                -0.070057  1.000000      0.045254  0.001790  0.468928   
arrival_time         -0.079846  0.045254      1.000000 -0.022188 -0.124206   
class                 0.029657  0.001790     -0.022188  1.000000  0.138937   
duration              0.131420  0.468928     -0.124206  0.138937  1.000000   
days_left             0.000081 -0.009128      0.000499 -0.012238 -0.039288   
price                 0.019681  0.120344     -0.000813  0.937923  0.204198   

                days_left     price  
departure_time   0.000081  0.019681  
stops           -0.009128  0.120344  
arrival_time     0.000499 -0.000813  
class           -0.012238  0.937923  
duration        -0.039288  0.204198  
days_left        1.000000 -0.091091  
price           -0.091091  1.000000

In [83]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, shuffle=False)

In [84]:
x_train

array([[ 3.  ,  0.  ,  4.  ,  0.  ,  2.17,  1.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  2.33,  1.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  2.17,  1.  ],
       ...,
       [ 3.  ,  1.  ,  3.  ,  1.  , 24.33, 31.  ],
       [ 1.  ,  1.  ,  3.  ,  1.  ,  6.58, 31.  ],
       [ 2.  ,  1.  ,  4.  ,  1.  ,  7.17, 31.  ]])

In [87]:
y_train

array([ 5953,  5953,  5956, ..., 53634, 58125, 58125], dtype=int64)

In [ ]:
coefficients = np.zeros(6)
print(coefficients)

Category  b
0        A  1
1        B  1
2        A  1
3        C  1
4        B  1

In [ ]:
x = df.iloc[0:, 0:6]
# x = np.array(x)
# # x = (x - x.mean()) / x.std()
# x = pd.DataFrame(x)
x['b'] = 1
x