In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler


In [3]:
df = pd.read_csv("Flight_Price_Dataset_Q2.csv")
df

departure_time stops   arrival_time     class  duration  days_left  \
0             Evening  zero          Night   Economy      2.17          1   
1       Early_Morning  zero        Morning   Economy      2.33          1   
2       Early_Morning  zero  Early_Morning   Economy      2.17          1   
3             Morning  zero      Afternoon   Economy      2.25          1   
4             Morning  zero        Morning   Economy      2.33          1   
...               ...   ...            ...       ...       ...        ...   
270133  Early_Morning   one          Night  Business     17.25         49   
270134        Morning   one        Evening  Business     10.08         49   
270135      Afternoon   one          Night  Business     10.42         49   
270136  Early_Morning   one        Evening  Business     10.00         49   
270137        Morning   one        Evening  Business     10.08         49   

        price  
0        5953  
1        5953  
2        5956  
3        5955  
4        5955  
...       ...  
270133  68739  
270134  69265  
270135  77105  
270136  81585  
270137  81585  

[270138 rows x 7 columns]

In [4]:
ohe = OneHotEncoder()
feature_array = ohe.fit_transform(df[['stops', 'arrival_time', 'departure_time']]).toarray()
labels = ["one", "two_or_more", "zero", "arrival_time_Afternoon", "arrival_time_Early_Morning", "arrival_time_Evening", "arrival_time_Late_Night", "arrival_time_Morning", "arrival_time_Night", "departure_time_Afternoon", "departure_time_Early_Morning", "departure_time_Evening", "departure_time_Late_Night", "departure_time_Morning", "departure_time_Night"]



In [5]:
dataframe = pd.DataFrame(feature_array, columns=labels)
df = df.drop("departure_time", axis=1)
df = df.drop("arrival_time", axis=1)
df = df.drop("stops", axis=1)
df = pd.concat([dataframe, df], axis=1)
df

one  two_or_more  zero  arrival_time_Afternoon  \
0       0.0          0.0   1.0                     0.0   
1       0.0          0.0   1.0                     0.0   
2       0.0          0.0   1.0                     0.0   
3       0.0          0.0   1.0                     1.0   
4       0.0          0.0   1.0                     0.0   
...     ...          ...   ...                     ...   
270133  1.0          0.0   0.0                     0.0   
270134  1.0          0.0   0.0                     0.0   
270135  1.0          0.0   0.0                     0.0   
270136  1.0          0.0   0.0                     0.0   
270137  1.0          0.0   0.0                     0.0   

        arrival_time_Early_Morning  arrival_time_Evening  \
0                              0.0                   0.0   
1                              0.0                   0.0   
2                              1.0                   0.0   
3                              0.0                   0.0   
4                              0.0                   0.0   
...                            ...                   ...   
270133                         0.0                   0.0   
270134                         0.0                   1.0   
270135                         0.0                   0.0   
270136                         0.0                   1.0   
270137                         0.0                   1.0   

        arrival_time_Late_Night  arrival_time_Morning  arrival_time_Night  \
0                           0.0                   0.0                 1.0   
1                           0.0                   1.0                 0.0   
2                           0.0                   0.0                 0.0   
3                           0.0                   0.0                 0.0   
4                           0.0                   1.0                 0.0   
...                         ...                   ...                 ...   
270133                      0.0                   0.0                 1.0   
270134                      0.0                   0.0                 0.0   
270135                      0.0                   0.0                 1.0   
270136                      0.0                   0.0                 0.0   
270137                      0.0                   0.0                 0.0   

        departure_time_Afternoon  departure_time_Early_Morning  \
0                            0.0                           0.0   
1                            0.0                           1.0   
2                            0.0                           1.0   
3                            0.0                           0.0   
4                            0.0                           0.0   
...                          ...                           ...   
270133                       0.0                           1.0   
270134                       0.0                           0.0   
270135                       1.0                           0.0   
270136                       0.0                           1.0   
270137                       0.0                           0.0   

        departure_time_Evening  departure_time_Late_Night  \
0                          1.0                        0.0   
1                          0.0                        0.0   
2                          0.0                        0.0   
3                          0.0                        0.0   
4                          0.0                        0.0   
...                        ...                        ...   
270133                     0.0                        0.0   
270134                     0.0                        0.0   
270135                     0.0                        0.0   
270136                     0.0                        0.0   
270137                     0.0                        0.0   

        departure_time_Morning  departure_time_Night     class  duration  \
0                          0.0                   0.0   Economy 

In [6]:
df['class'] = df['class'].map({'Economy': 1, 'Business': 5})
df.corr()
# data = np.array(df)
# scaler = MinMaxScaler()
# normalized = scaler.fit_transform(data)
# normalized

one  two_or_more      zero  \
one                           1.000000    -0.484328 -0.833693   
two_or_more                  -0.484328     1.000000 -0.079357   
zero                         -0.833693    -0.079357  1.000000   
arrival_time_Afternoon       -0.004575    -0.033350  0.026263   
arrival_time_Early_Morning   -0.015368    -0.004172  0.020144   
arrival_time_Evening          0.053644     0.020958 -0.074351   
arrival_time_Late_Night      -0.023734     0.002853  0.025241   
arrival_time_Morning         -0.030226    -0.016025  0.044555   
arrival_time_Night           -0.002917     0.018960 -0.008645   
departure_time_Afternoon      0.011143     0.028860 -0.030913   
departure_time_Early_Morning -0.020932     0.029609  0.005161   
departure_time_Evening       -0.024173    -0.019732  0.039997   
departure_time_Late_Night    -0.033276    -0.004438  0.040716   
departure_time_Morning        0.025305     0.027945 -0.046472   
departure_time_Night          0.016447    -0.071785  0.026571   
class                         0.120200    -0.106752 -0.069574   
duration                      0.400803     0.092975 -0.515362   
days_left                     0.010852    -0.018647 -0.000595   
price                         0.200399    -0.064174 -0.187828   

                              arrival_time_Afternoon  \
one                                        -0.004575   
two_or_more                                -0.033350   
zero                                        0.026263   
arrival_time_Afternoon                      1.000000   
arrival_time_Early_Morning                 -0.088747   
arrival_time_Evening                       -0.226516   
arrival_time_Late_Night                    -0.084422   
arrival_time_Morning                       -0.195900   
arrival_time_Night                         -0.252574   
departure_time_Afternoon                   -0.060540   
departure_time_Early_Morning                0.095253   
departure_time_Evening                     -0.069498   
departure_time_Late_Night                  -0.013874   
departure_time_Morning                      0.036572   
departure_time_Night                       -0.009478   
class                                      -0.021143   
duration                                   -0.044055   
days_left                                  -0.001552   
price                                      -0.040850   

                              arrival_time_Early_Morning  \
one                                            -0.015368   
two_or_more                                    -0.004172   
zero                                            0.020144   
arrival_time_Afternoon                         -0.088747   
arrival_time_Early_Morning                      1.000000   
arrival_time_Evening                           -0.138341   
arrival_time_Late_Night                        -0.051560   
arrival_time_Morning                           -0.119643   
arrival_time_Night                             -0.154256   
departure_time_Afternoon                       -0.049979   
departure_time_Early_Morning                   -0.009012   
departure_time_Evening                          0.045832   
departure_time_Late_Night                       0.098631   
departure_time_Morning                         -0.071120   
departure_time_Night                            0.073238   
class                                          -0.041662   
duration                                        0.010889   
days_left                                       0.019231   
price                                          -0.060150   

                              arrival_time_Evening  arrival_time_Late_Night  \
one                                       0.053644                -0.023734   
two_or_more                               0.020958                 0.002853   
zero                                     -0.074351                 0.025241   
arrival_time_Afternoon                   -0.226516                -0.084422   
arrival_time_Earl

In [31]:
x = df.drop("price", axis=1).values
y = df["price"].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.6, shuffle=False)
x_train

array([[ 0.  ,  0.  ,  1.  , ...,  1.  ,  2.17,  1.  ],
       [ 0.  ,  0.  ,  1.  , ...,  1.  ,  2.33,  1.  ],
       [ 0.  ,  0.  ,  1.  , ...,  1.  ,  2.17,  1.  ],
       ...,
       [ 1.  ,  0.  ,  0.  , ...,  1.  , 10.75,  4.  ],
       [ 1.  ,  0.  ,  0.  , ...,  1.  , 11.58,  4.  ],
       [ 1.  ,  0.  ,  0.  , ...,  1.  , 14.08,  4.  ]])

In [32]:

df["stops"] = df["stops"].map({"zero": 0, "one": 1, "two_or_more": 2})

df['arrival_time'] = df['arrival_time'].map({'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2,
                                             'Evening': 3, 'Night': 4, 'Late_Night': 5})

df['departure_time'] = df['departure_time'].map({'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2,
                                                 'Evening': 3, 'Night': 4, 'Late_Night': 5})

df['class'] = df['class'].map({'Economy': 0, 'Business': 1})
df

KeyError: 'stops'

In [44]:
x = df.iloc[0:,0:18]
x['19'] = 1
x

one  two_or_more  zero  arrival_time_Afternoon  \
0       0.0          0.0   1.0                     0.0   
1       0.0          0.0   1.0                     0.0   
2       0.0          0.0   1.0                     0.0   
3       0.0          0.0   1.0                     1.0   
4       0.0          0.0   1.0                     0.0   
...     ...          ...   ...                     ...   
270133  1.0          0.0   0.0                     0.0   
270134  1.0          0.0   0.0                     0.0   
270135  1.0          0.0   0.0                     0.0   
270136  1.0          0.0   0.0                     0.0   
270137  1.0          0.0   0.0                     0.0   

        arrival_time_Early_Morning  arrival_time_Evening  \
0                              0.0                   0.0   
1                              0.0                   0.0   
2                              1.0                   0.0   
3                              0.0                   0.0   
4                              0.0                   0.0   
...                            ...                   ...   
270133                         0.0                   0.0   
270134                         0.0                   1.0   
270135                         0.0                   0.0   
270136                         0.0                   1.0   
270137                         0.0                   1.0   

        arrival_time_Late_Night  arrival_time_Morning  arrival_time_Night  \
0                           0.0                   0.0                 1.0   
1                           0.0                   1.0                 0.0   
2                           0.0                   0.0                 0.0   
3                           0.0                   0.0                 0.0   
4                           0.0                   1.0                 0.0   
...                         ...                   ...                 ...   
270133                      0.0                   0.0                 1.0   
270134                      0.0                   0.0                 0.0   
270135                      0.0                   0.0                 1.0   
270136                      0.0                   0.0                 0.0   
270137                      0.0                   0.0                 0.0   

        departure_time_Afternoon  departure_time_Early_Morning  \
0                            0.0                           0.0   
1                            0.0                           1.0   
2                            0.0                           1.0   
3                            0.0                           0.0   
4                            0.0                           0.0   
...                          ...                           ...   
270133                       0.0                           1.0   
270134                       0.0                           0.0   
270135                       1.0                           0.0   
270136                       0.0                           1.0   
270137                       0.0                           0.0   

        departure_time_Evening  departure_time_Late_Night  \
0                          1.0                        0.0   
1                          0.0                        0.0   
2                          0.0                        0.0   
3                          0.0                        0.0   
4                          0.0                        0.0   
...                        ...                        ...   
270133                     0.0                        0.0   
270134                     0.0                        0.0   
270135                     0.0                        0.0   
270136                     0.0                        0.0   
270137                     0.0                        0.0   

        departure_time_Morning  departure_time_Night  class  duration  \
0                          0.0                   0.0      1      2

In [46]:
y = np.array(df.iloc[0:, 18:])
y

array([[ 5953],
       [ 5953],
       [ 5956],
       ...,
       [77105],
       [81585],
       [81585]], dtype=int64)

In [33]:
y = df["price"].values
print(y)

[ 5953  5953  5956 ... 77105 81585 81585]


In [34]:
df.corr()

one  two_or_more      zero  \
one                           1.000000    -0.484328 -0.833693   
two_or_more                  -0.484328     1.000000 -0.079357   
zero                         -0.833693    -0.079357  1.000000   
arrival_time_Afternoon       -0.004575    -0.033350  0.026263   
arrival_time_Early_Morning   -0.015368    -0.004172  0.020144   
arrival_time_Evening          0.053644     0.020958 -0.074351   
arrival_time_Late_Night      -0.023734     0.002853  0.025241   
arrival_time_Morning         -0.030226    -0.016025  0.044555   
arrival_time_Night           -0.002917     0.018960 -0.008645   
departure_time_Afternoon      0.011143     0.028860 -0.030913   
departure_time_Early_Morning -0.020932     0.029609  0.005161   
departure_time_Evening       -0.024173    -0.019732  0.039997   
departure_time_Late_Night    -0.033276    -0.004438  0.040716   
departure_time_Morning        0.025305     0.027945 -0.046472   
departure_time_Night          0.016447    -0.071785  0.026571   
class                         0.120200    -0.106752 -0.069574   
duration                      0.400803     0.092975 -0.515362   
days_left                     0.010852    -0.018647 -0.000595   
price                         0.200399    -0.064174 -0.187828   

                              arrival_time_Afternoon  \
one                                        -0.004575   
two_or_more                                -0.033350   
zero                                        0.026263   
arrival_time_Afternoon                      1.000000   
arrival_time_Early_Morning                 -0.088747   
arrival_time_Evening                       -0.226516   
arrival_time_Late_Night                    -0.084422   
arrival_time_Morning                       -0.195900   
arrival_time_Night                         -0.252574   
departure_time_Afternoon                   -0.060540   
departure_time_Early_Morning                0.095253   
departure_time_Evening                     -0.069498   
departure_time_Late_Night                  -0.013874   
departure_time_Morning                      0.036572   
departure_time_Night                       -0.009478   
class                                      -0.021143   
duration                                   -0.044055   
days_left                                  -0.001552   
price                                      -0.040850   

                              arrival_time_Early_Morning  \
one                                            -0.015368   
two_or_more                                    -0.004172   
zero                                            0.020144   
arrival_time_Afternoon                         -0.088747   
arrival_time_Early_Morning                      1.000000   
arrival_time_Evening                           -0.138341   
arrival_time_Late_Night                        -0.051560   
arrival_time_Morning                           -0.119643   
arrival_time_Night                             -0.154256   
departure_time_Afternoon                       -0.049979   
departure_time_Early_Morning                   -0.009012   
departure_time_Evening                          0.045832   
departure_time_Late_Night                       0.098631   
departure_time_Morning                         -0.071120   
departure_time_Night                            0.073238   
class                                          -0.041662   
duration                                        0.010889   
days_left                                       0.019231   
price                                          -0.060150   

                              arrival_time_Evening  arrival_time_Late_Night  \
one                                       0.053644                -0.023734   
two_or_more                               0.020958                 0.002853   
zero                                     -0.074351                 0.025241   
arrival_time_Afternoon                   -0.226516                -0.084422   
arrival_time_Earl

In [35]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, shuffle=False)

In [36]:
x_train

array([[ 0.  ,  0.  ,  1.  , ...,  1.  ,  2.17,  1.  ],
       [ 0.  ,  0.  ,  1.  , ...,  1.  ,  2.33,  1.  ],
       [ 0.  ,  0.  ,  1.  , ...,  1.  ,  2.17,  1.  ],
       ...,
       [ 1.  ,  0.  ,  0.  , ...,  5.  , 24.33, 31.  ],
       [ 1.  ,  0.  ,  0.  , ...,  5.  ,  6.58, 31.  ],
       [ 1.  ,  0.  ,  0.  , ...,  5.  ,  7.17, 31.  ]])

In [37]:
y_train

array([ 5953,  5953,  5956, ..., 53634, 58125, 58125], dtype=int64)

In [ ]:
coefficients = np.zeros(6)
print(coefficients)

In [87]:
y_train

array([ 5953,  5953,  5956, ..., 53634, 58125, 58125], dtype=int64)

In [90]:
coefficients = np.zeros(6)
print(coefficients)

[0. 0. 0. 0. 0. 0.]
